/**
 * @fileoverview gRPC-Web generated client stub for IVM.slam
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: slam_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var pointcloud_pb = require('./pointcloud_pb.js')
const proto = {};
proto.IVM = {};
proto.IVM.slam = require('./slam_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.IVM.slam.SlamServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.IVM.slam.SlamServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.IVM.slam.PointCloud>}
 */
const methodDescriptor_SlamService_GetPointCloud = new grpc.web.MethodDescriptor(
  '/IVM.slam.SlamService/GetPointCloud',
  grpc.web.MethodType.SERVER_STREAMING,
  google_protobuf_empty_pb.Empty,
  pointcloud_pb.PointCloud,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  pointcloud_pb.PointCloud.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PointCloud>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServiceClient.prototype.getPointCloud =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPointCloud',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPointCloud);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PointCloud>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServicePromiseClient.prototype.getPointCloud =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPointCloud',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPointCloud);
};


module.exports = proto.IVM.slam;

